bd-7 feat: add input component
itBanda/ui-kit pull request #10
Opened 2024-09-05 19:28 UTC by SlavaMryasov

2024-09-06 08:48 UTC, sfgardev requested changes

2024-09-06 08:48 UTC, sfgardev commented on src/components/input/Input.tsx
> +          'focus-within:border-accent-500',
use focus on input (semantically right to use it in input)
https://bharathvaj-ganesan.medium.com/focus-vs-focus-within-vs-focus-visible-2db18593495b

2024-09-06 08:48 UTC, sfgardev commented on src/components/input/Input.tsx
> +        <span className='block text-sm text-danger-500'>{errorText}</span>
use p instead

2024-09-06 08:48 UTC, sfgardev commented on src/components/input/Password.stories.ts
> +export const Default: Story<typeof meta> = {
use StoryObj, remove redundant abstraction

2024-09-06 09:19 UTC, SlavaMryasov commented on src/components/input/Input.tsx
> +  icon,
done

2024-09-06 09:34 UTC, SlavaMryasov commented on src/components/input/Input.tsx
> +  const id = useId()
done

2024-09-06 09:38 UTC, SlavaMryasov commented on src/components/input/Input.tsx
> +  const positionIcon = type === 'search' ? 'flex-row-reverse justify-end' : ''
done

2024-09-06 09:43 UTC, SlavaMryasov commented on src/components/input/Input.tsx
> +            // 'disabled:custom-block-cursor',
done

2024-09-06 09:44 UTC, SlavaMryasov commented on src/components/input/Input.tsx
> +          'relative inline-flex h-9 items-center rounded-sm border border-dark-100 text-light-900',
remove inline-flex and add w-280

2024-09-06 09:45 UTC, SlavaMryasov commented on src/components/input/Input.tsx
> +          `${disabled && 'text-dark-100'}`,
done for desabled

2024-09-06 09:46 UTC, SlavaMryasov commented on src/components/input/Input.tsx
> +        ></input>
done

2024-09-06 15:50 UTC, SlavaMryasov commented on src/components/input/Input.tsx
> +          'focus-within:border-accent-500',
done

2024-09-06 15:50 UTC, SlavaMryasov commented on src/components/input/Input.tsx
> +        <span className='block text-sm text-danger-500'>{errorText}</span>
done

2024-09-06 15:53 UTC, SlavaMryasov commented on src/components/input/Password.stories.ts
> +export const Default: Story<typeof meta> = {
done

2024-09-06 18:03 UTC, SlavaMryasov commented
please review the corrections

2024-09-07 08:48 UTC, sfgardev requested changes

2024-09-07 08:48 UTC, sfgardev commented on src/components/input/Input.tsx
>            className={cn(
you can write clsx classes lile this {'bg-red: errorText'}

2024-09-07 08:48 UTC, sfgardev commented on src/components/input/Input.tsx
> +            <Icon className={iconColor} icon='eye-off-outline' />
input component should be independent from icon (if eye-off-outline be deleted,  we need to fix input)

2024-09-07 09:05 UTC, sfgardev approved these changes

2024-09-07 09:07 UTC, itBanda approved these changes

2024-09-07 09:09 UTC, closed without merging