Bd 9 chore add checkbox component
itBanda/ui-kit pull request #16
Opened 2024-09-09 09:02 UTC by KateTernovskaya

2024-09-09 09:52 UTC, SlavaMryasov requested changes

2024-09-09 09:52 UTC, SlavaMryasov commented on src/components/checkbox/Checkbox.tsx
> +} & DefaultCheckboxProps
instead of creating two types you can create one type, name it Props  and use ComponentProps from React
example:
export type Props = {
 label?: string
} & ComponentProps<'checkbox'>

2024-09-09 11:18 UTC, sfgardev requested changes

2024-09-09 13:02 UTC, sfgardev commented on src/components/checkbox/Checkbox.tsx
> +  ({ checked, id, label, ...props }, ref) => {
you do not need to pass checked prop, it will be in ...props

2024-09-09 13:05 UTC, sfgardev commented on src/components/checkbox/Checkbox.tsx
> +              'group-focus-within:bg-dark-500 group-hover:bg-dark-300 group-active:bg-dark-100':
div in label is not semantically correct, focus, focus:within, focus:visible should be used on input element

2024-09-09 13:11 UTC, sfgardev commented on src/components/checkbox/Checkbox.tsx
> +            onChange={props.onChange}
remove onChange

2024-09-09 13:13 UTC, sfgardev commented on src/components/checkbox/Checkbox.tsx
> +                !props.disabled,
you can destructure disabled from props

2024-09-09 13:14 UTC, sfgardev commented on src/components/checkbox/Checkbox.tsx
> +              { 'border-none bg-dark-100': props.disabled }
you can destructure disabled from props

2024-09-09 13:15 UTC, sfgardev commented on src/components/checkbox/Checkbox.tsx
> +                  'absolute left-1/2 top-1/2 h-5 w-5 -translate-x-1/2 -translate-y-1/2 transform text-dark-900',
translate 2times?

2024-09-09 13:16 UTC, sfgardev commented on src/components/checkbox/Checkbox.tsx
> +)
add to the bottom Checkbox.displayName = 'Checkbox'

2024-09-11 10:24 UTC, KateTernovskaya commented on src/components/checkbox/Checkbox.tsx
> +} & DefaultCheckboxProps
done

2024-09-11 10:24 UTC, KateTernovskaya commented on src/components/checkbox/Checkbox.tsx
> +  const [isChecked, setIsChecked] = useState(checked)
done

2024-09-11 10:24 UTC, KateTernovskaya commented on src/components/checkbox/Checkbox.tsx
> +  const handleCheckboxChange = () => {
done

2024-09-11 10:24 UTC, KateTernovskaya commented on src/components/checkbox/Checkbox.tsx
> +  id?: string
done

2024-09-11 10:24 UTC, KateTernovskaya commented on src/components/checkbox/Checkbox.tsx
> +  ({ checked, id, label, ...props }, ref) => {
done

2024-09-11 10:25 UTC, KateTernovskaya commented on src/components/checkbox/Checkbox.tsx
> +              'group-focus-within:bg-dark-500 group-hover:bg-dark-300 group-active:bg-dark-100':
done

2024-09-11 10:25 UTC, KateTernovskaya commented on src/components/checkbox/Checkbox.tsx
> +    const checkboxId = id ?? uniqueId
done

2024-09-11 10:25 UTC, KateTernovskaya commented on src/components/checkbox/Checkbox.tsx
> +            onChange={props.onChange}
done

2024-09-11 10:25 UTC, KateTernovskaya commented on src/components/checkbox/Checkbox.tsx
> +                !props.disabled,
done

2024-09-11 10:25 UTC, KateTernovskaya commented on src/components/checkbox/Checkbox.tsx
> +            checked={checked}
done

2024-09-11 10:25 UTC, KateTernovskaya commented on src/components/checkbox/Checkbox.tsx
> +              'absolute h-full w-full cursor-pointer opacity-0 disabled:cursor-not-allowed'
done

2024-09-11 10:25 UTC, KateTernovskaya commented on src/components/checkbox/Checkbox.tsx
> +            disabled={props.disabled}
done

2024-09-11 10:25 UTC, KateTernovskaya commented on src/components/checkbox/Checkbox.tsx
> +              { 'border-none bg-dark-100': props.disabled }
done

2024-09-11 10:25 UTC, KateTernovskaya commented on src/components/checkbox/Checkbox.tsx
> +                  'absolute left-1/2 top-1/2 h-5 w-5 -translate-x-1/2 -translate-y-1/2 transform text-dark-900',
done

2024-09-11 10:25 UTC, KateTernovskaya commented on src/components/checkbox/Checkbox.tsx
> +)
done

2024-09-11 16:05 UTC, merged