BD-10 feat: add button component
itBanda/ui-kit pull request #17
Opened 2024-09-09 14:07 UTC by pRomKol

2024-09-09 17:23 UTC, SlavaMryasov requested changes
make the components behave as in the design

2024-09-09 17:23 UTC, SlavaMryasov commented on src/components/button/Button.tsx
> +          ' enabled:hover:bg-dark-100 active:bg-dark-500  focus:outline-accent-500',
focus doesn't work everywhere

2024-09-09 17:23 UTC, SlavaMryasov commented on src/components/button/Button.tsx
> +        class: 'text-accent-900 opacity-50 border-accent-700',
where did you get opacity, remove!

2024-09-11 08:17 UTC, pRomKol commented on src/components/button/Button.tsx
> +export type Props = ComponentProps<'button'> &
done.

2024-09-11 08:18 UTC, pRomKol commented on src/components/button/Button.tsx
> +      className={twMerge(cn(buttonVariants({ disabled, variant }), className))}
done

2024-09-11 08:18 UTC, pRomKol commented on src/components/button/Button.tsx
> +  disabled = false,
done

2024-09-11 08:18 UTC, pRomKol commented on src/components/button/Button.tsx
> +          ' enabled:hover:border-accent-100 enabled:hover:text-accent-100 active:text-accent-700 active:border-accent-700',
done

2024-09-11 08:18 UTC, pRomKol commented on src/components/button/Button.tsx
> +          ' enabled:hover:bg-accent-100 active:bg-accent-700 active: text-light-500',
done

2024-09-11 08:18 UTC, pRomKol commented on src/components/button/Button.tsx
> +          ' enabled:hover:bg-dark-100 active:bg-dark-500  focus:outline-accent-500',
done

2024-09-11 08:18 UTC, pRomKol commented on src/components/button/Button.tsx
> +        class: 'text-accent-900 opacity-50 border-accent-700',
done

2024-09-11 08:58 UTC, sfgardev commented on package.json
> +    "class-variance-authority": "^0.7.0",
remove ^ from version

2024-09-11 09:01 UTC, pRomKol commented on package.json
> +    "class-variance-authority": "^0.7.0",
done

2024-09-11 17:48 UTC, SlavaMryasov approved these changes

2024-09-11 17:49 UTC, merged