BD-21 feat: add start version of modal component
itBanda/ui-kit pull request #27
Opened 2024-09-17 05:48 UTC by pRomKol

2024-09-17 09:24 UTC, sfgardev requested changes

2024-09-17 09:24 UTC, sfgardev commented on src/components/modal/Modal.stories.ts
> +    title: 'some title',
<img width="777" alt="image" src="https://github.com/user-attachments/assets/871949fa-e606-46c9-85e8-f0f95957017a">

2024-09-17 09:24 UTC, sfgardev commented on src/components/modal/Modal.tsx
> +        <Icon
add cursor pointer to close icon

2024-09-17 09:24 UTC, sfgardev commented on src/components/modal/Modal.tsx
> +      <div className={cn('flex flex-col px-[24px] text-white', className)}>
add vertical padding

2024-09-17 09:24 UTC, sfgardev commented on src/components/modal/Modal.tsx
> +    <div
modal should have some max-width, should be in overlay

2024-09-17 09:27 UTC, sfgardev commented
and add index.ts reexport in modal folder and also export in src/index.ts

2024-09-18 10:22 UTC, pRomKol commented on src/components/modal/Modal.stories.ts
> +  title: 'Modal',
done

2024-09-18 10:22 UTC, pRomKol commented on src/components/modal/Modal.tsx
> +}: ModalProps & PropsWithChildren<{ className?: string }>) => {
done

2024-09-18 10:22 UTC, pRomKol commented on src/components/modal/Modal.stories.ts
> +    title: 'some title',
done

2024-09-18 10:22 UTC, pRomKol commented on src/components/modal/Modal.tsx
> +        <Icon
done

2024-09-18 10:23 UTC, pRomKol commented on src/components/modal/Modal.tsx
> +      <div className={cn('flex flex-col px-[24px] text-white', className)}>
done

2024-09-18 10:23 UTC, pRomKol commented on src/components/modal/Modal.tsx
> +    <div
done

2024-09-21 12:05 UTC, sfgardev requested changes

2024-09-22 19:21 UTC, pRomKol commented on src/components/modal/Modal.tsx
> +          'w-fit max-w-[500px] divide-y-[1px] divide-dark-100 rounded-sm border border-dark-100 bg-dark-300'
done

2024-09-22 19:21 UTC, pRomKol commented on src/components/modal/Modal.tsx
> +  className?: string
done

2024-09-22 19:21 UTC, pRomKol commented on src/components/modal/Modal.tsx
> +}: ModalProps & PropsWithChildren<{ className?: string }>) => {
done

2024-09-22 19:22 UTC, pRomKol commented on src/components/modal/Modal.stories.ts
> +export const Default: StoryObj<typeof Modal> = {
done

2024-09-22 19:22 UTC, pRomKol commented on src/components/modal/index.ts
> +export { Modal } from './Modal'
done

2024-09-22 19:22 UTC, pRomKol commented on src/components/modal/Modal.tsx
> +export const Modal = ({
done

2024-09-23 15:53 UTC, sfgardev approved these changes

2024-09-23 15:56 UTC, merged