BD-9 fix: add pointer-events-none
itBanda/ui-kit pull request #30
Opened 2024-09-27 12:24 UTC by KateTernovskaya

2024-09-27 15:04 UTC, sfgardev requested changes

2024-09-27 15:04 UTC, sfgardev commented on src/components/checkbox/Checkbox.tsx
> +                  'pointer-events-none absolute left-1/2 top-1/2 h-5 w-5 -translate-x-1/2 -translate-y-1/2 cursor-pointer',
you can remove pointer-events from icon

2024-10-01 06:53 UTC, KateTernovskaya commented on src/components/checkbox/Checkbox.tsx
> +                  'pointer-events-none absolute left-1/2 top-1/2 h-5 w-5 -translate-x-1/2 -translate-y-1/2 cursor-pointer',
done

2024-10-01 08:13 UTC, sfgardev approved these changes

2024-10-01 08:14 UTC, merged