BD-51 feat: text area
itBanda/ui-kit pull request #36
Opened 2024-10-09 08:54 UTC by KateTernovskaya

2024-10-14 06:34 UTC, sfgardev requested changes
forgot to add re-export into src/index.ts

2024-10-14 06:34 UTC, sfgardev commented on src/components/text-area/TextArea.tsx
> +            {
<img width="663" alt="image" src="https://github.com/user-attachments/assets/c6380a02-d5ae-443b-a83b-0c09bf0f689e">

2024-10-14 06:34 UTC, sfgardev commented on src/components/text-area/TextArea.stories.tsx
> +    defaultValue: 'Text area',
maybe add placeholder instead of defaultValue

2024-10-22 07:22 UTC, KateTernovskaya commented on src/components/text-area/TextArea.stories.tsx
> +    defaultValue: 'Text area',
defaultValue was set to see text styles

2024-10-22 09:47 UTC, sfgardev approved these changes

2024-10-22 09:48 UTC, merged