Feat/bd 50 create tab component
itBanda/ui-kit pull request #37
Opened 2024-10-10 13:07 UTC by legkovaAnastasia

2024-10-11 10:50 UTC, sfgardev requested changes
you forgot to add re-export to index file in src/index.ts

2024-10-11 10:50 UTC, sfgardev commented on package.json
> +    "@radix-ui/react-tabs": "^1.1.1",
remove ^ to fix version

2024-10-11 10:50 UTC, sfgardev commented on package.json
> +    "react-tabs": "^6.0.2",
i do not see where are you using it

2024-10-11 10:50 UTC, sfgardev commented on src/components/tab/Tab.stories.tsx
i think the story should be named Tabs.stories

2024-10-11 10:50 UTC, sfgardev commented on src/components/tab/Tab.tsx
i think the component should be named Tabs

2024-10-11 10:50 UTC, sfgardev commented on src/components/tab/Tab.tsx
> +  ({ TabData, ...props }, ref) => {
you do not use props anywhere

2024-10-11 10:50 UTC, sfgardev commented on src/components/tab/Tab.tsx
> +export type TabProps = {
you can call it just Props or TabsProps and why do you export if you do not use it anywhere else?

2024-10-11 10:50 UTC, sfgardev commented on src/components/tab/Tab.tsx
> +        defaultValue={TabData[0].value}
<img width="383" alt="image" src="https://github.com/user-attachments/assets/8607a121-8edd-4b0b-8fa7-ef321851da0d">

you can use optional chaining

2024-10-11 10:50 UTC, sfgardev commented on src/components/tab/Tab.tsx
> +  TabData: Array<{
why TabData starts whith uppercase? and it should be tabsData

2024-10-11 13:57 UTC, legkovaAnastasia commented on src/components/tab/Tab.tsx
I cant name component Tabs, because it should be imported from radix like Tabs, maybe TabsComponent, TabsMenu?

2024-10-11 14:03 UTC, legkovaAnastasia commented on package.json
> +    "@radix-ui/react-tabs": "^1.1.1",
Done

2024-10-11 14:06 UTC, legkovaAnastasia commented on src/components/tab/Tab.tsx
> +        defaultValue={TabData[0].value}
Ok

2024-10-11 14:06 UTC, legkovaAnastasia commented on src/components/tab/Tab.tsx
> +  TabData: Array<{
Done

2024-10-13 14:20 UTC, sfgardev commented on src/components/tab/Tab.tsx
you can use import * as RadixTabs from '@radix-ui/react-tabs'

2024-10-14 08:55 UTC, legkovaAnastasia commented on src/components/tab/Tab.stories.tsx
ok

2024-10-14 08:55 UTC, legkovaAnastasia commented on src/components/tab/Tab.tsx
ok

2024-10-14 08:57 UTC, legkovaAnastasia commented on src/components/tab/Tab.tsx
> +  ({ TabData, ...props }, ref) => {
done

2024-10-14 08:58 UTC, legkovaAnastasia commented on src/components/tab/Tab.tsx
> +export type TabProps = {
ok

2024-10-16 06:46 UTC, sfgardev requested changes

2024-10-16 06:46 UTC, sfgardev commented on src/components/tabs/Tabs.tsx
> +        className='flex h-9 w-[972px] flex-col pt-6'
remove width, because it is not flexible on small resolutions

2024-10-16 06:46 UTC, sfgardev commented on src/components/tabs/Tabs.tsx
> +                      'data-[state=active]:text-accent-500'
you can use one cn here without ternary, like this {some styles: tabs.disabled } and also you will avoid class duplications

2024-10-16 06:46 UTC, sfgardev commented
you forgot to add re-export to index file in src/index.ts

2024-10-16 11:40 UTC, sfgardev approved these changes

2024-10-16 11:42 UTC, merged