BD-52 Add Sidebar component
itBanda/ui-kit pull request #38
Opened 2024-10-11 07:06 UTC by pRomKol

2024-10-11 11:07 UTC, sfgardev commented
![image](https://github.com/user-attachments/assets/55000639-c7a8-4720-a805-e1e7dbf9e0da)

2024-10-11 11:29 UTC, sfgardev requested changes

2024-10-11 11:29 UTC, sfgardev commented on src/components/sidebar/Sidebar.tsx
> +          }
you should pass className without curly braces!

2024-10-11 11:29 UTC, sfgardev commented on src/components/sidebar/Sidebar.tsx
> +  className?: string
componentProps already has className

2024-10-11 11:29 UTC, sfgardev commented on src/components/sidebar/index.ts
you forgot to add re-export to index file in src/index.ts

2024-10-11 11:29 UTC, sfgardev commented on src/components/sidebar/Sidebar.stories.tsx
> +                  <Icon icon={el.icon} />
<img width="709" alt="image" src="https://github.com/user-attachments/assets/2497e91e-d2f0-4334-b99d-6e9fdfa2cb41">

2024-10-11 11:29 UTC, sfgardev commented on src/components/sidebar/Sidebar.stories.tsx
> +        <nav className='flex flex-col items-center pb-[35px] pt-[72px] font-medium text-light-100'>
i think we can move spacings inside sidebar component and make it according to design

2024-10-11 11:29 UTC, sfgardev commented on src/components/sidebar/Sidebar.stories.tsx
> +                  <Icon icon={el.icon} />
![image](https://github.com/user-attachments/assets/dec3ca8e-3c30-48b3-bb7a-8e23ded27286)

2024-10-11 11:29 UTC, sfgardev commented on src/components/sidebar/Sidebar.stories.tsx
> +            </Button>
you can add icon inside button

2024-10-11 11:29 UTC, sfgardev commented on src/components/sidebar/Sidebar.stories.tsx
> +                className='min-w-[121.05px] transition hover:text-accent-100'
why you add min-width:121.05px?

2024-10-11 11:29 UTC, sfgardev commented on src/components/sidebar/Sidebar.stories.tsx
> +          <div className='mt-auto flex min-w-[121.05px] gap-[12px] transition hover:text-accent-100'>
why you add min-width:121.05px?

2024-10-11 11:29 UTC, sfgardev commented on src/components/sidebar/Sidebar.stories.tsx
> +          <ul className='flex flex-col gap-[24px]'>
instead of using gap-[24px], use tailwind spaces (24/4 = 6)

2024-10-11 11:29 UTC, sfgardev commented on src/components/sidebar/Sidebar.stories.tsx
> +                <a className='flex gap-[12px]' href={el.href}>
use tailwind spaces

2024-10-11 11:29 UTC, sfgardev commented on src/components/sidebar/Sidebar.stories.tsx
> +                <a className='flex gap-[12px]' href={el.href}>
use tailwind spaces

2024-10-15 06:02 UTC, pRomKol commented on src/components/sidebar/Sidebar.tsx
> +          }
done

2024-10-15 06:02 UTC, pRomKol commented on src/components/sidebar/Sidebar.tsx
> +  className?: string
done

2024-10-15 06:02 UTC, pRomKol commented on src/components/sidebar/index.ts
done

2024-10-15 06:03 UTC, pRomKol commented on src/components/sidebar/Sidebar.stories.tsx
> +                  <Icon icon={el.icon} />
done

2024-10-15 06:03 UTC, pRomKol commented on src/components/sidebar/Sidebar.stories.tsx
> +        <nav className='flex flex-col items-center pb-[35px] pt-[72px] font-medium text-light-100'>
done

2024-10-15 06:03 UTC, pRomKol commented on src/components/sidebar/Sidebar.stories.tsx
> +                  <Icon icon={el.icon} />
done

2024-10-15 06:04 UTC, pRomKol commented on src/components/sidebar/Sidebar.stories.tsx
> +            </Button>
done

2024-10-15 06:04 UTC, pRomKol commented on src/components/sidebar/Sidebar.stories.tsx
> +                className='min-w-[121.05px] transition hover:text-accent-100'
done

2024-10-15 06:04 UTC, pRomKol commented on src/components/sidebar/Sidebar.stories.tsx
> +          <div className='mt-auto flex min-w-[121.05px] gap-[12px] transition hover:text-accent-100'>
fixed

2024-10-15 06:04 UTC, pRomKol commented on src/components/sidebar/Sidebar.stories.tsx
> +          <ul className='flex flex-col gap-[24px]'>
done

2024-10-15 06:04 UTC, pRomKol commented on src/components/sidebar/Sidebar.stories.tsx
> +                <a className='flex gap-[12px]' href={el.href}>
done

2024-10-15 06:04 UTC, pRomKol commented on src/components/sidebar/Sidebar.stories.tsx
> +                <a className='flex gap-[12px]' href={el.href}>
done

2024-10-16 07:01 UTC, sfgardev requested changes

2024-10-16 07:01 UTC, sfgardev commented on src/components/sidebar/Sidebar.stories.tsx
> +      <SideBar>
<img width="861" alt="image" src="https://github.com/user-attachments/assets/34530559-580f-4c6d-afee-013b23d9a64f">

you can add full screen height

2024-10-16 11:47 UTC, sfgardev requested changes

2024-10-16 11:47 UTC, sfgardev commented on src/components/sidebar/Sidebar.stories.tsx
> +        <nav className='h-fullп flex flex-col items-center self-start font-medium text-light-100'>
mistake was made)

2024-10-16 11:47 UTC, sfgardev commented on src/components/sidebar/Sidebar.tsx
> +          'flex h-[100vh] w-[220px] justify-center overflow-y-auto border-r border-dark-300',
no need to add height here, add it in stories
and add it like this h-dvh

2024-10-16 13:58 UTC, sfgardev approved these changes

2024-10-16 13:58 UTC, merged