Feat/bd 57 add alert component
itBanda/ui-kit pull request #40
Opened 2024-10-15 16:27 UTC by SlavaMryasov

2024-10-16 06:29 UTC, sfgardev requested changes

2024-10-16 06:29 UTC, sfgardev commented on src/components/alert/Alert.tsx
forgot to add re-exports

2024-10-16 06:29 UTC, sfgardev commented on src/components/alert/Alert.tsx
> +          'flex h-12 w-[387px] flex-row justify-between border px-[24px] pb-[12px] pt-[12px] text-light-100',
1.remove height
<img width="725" alt="image" src="https://github.com/user-attachments/assets/e0a0a8e1-72f6-4d7f-9654-e9fc4ca6e829">

2.do not use arbitrary values if possible

2024-10-16 06:29 UTC, sfgardev commented on src/components/alert/Alert.tsx
> +            className,
replace className from object

2024-10-16 06:29 UTC, sfgardev commented on src/components/alert/Alert.tsx
> +          {type === 'error' && <b>Error! </b>}
like in design, but looks strange, we should discuss it

2024-10-16 10:11 UTC, SlavaMryasov commented on src/components/alert/Alert.tsx
done

2024-10-16 10:18 UTC, SlavaMryasov commented on src/components/alert/Alert.tsx
> +          'flex h-12 w-[387px] flex-row justify-between border px-[24px] pb-[12px] pt-[12px] text-light-100',
done

2024-10-16 10:18 UTC, SlavaMryasov commented on src/components/alert/Alert.tsx
> +            className,
done

2024-10-16 10:18 UTC, SlavaMryasov commented on src/components/alert/Alert.tsx
> +          {type === 'error' && <b>Error! </b>}
done

2024-10-17 08:14 UTC, sfgardev approved these changes

2024-10-17 08:14 UTC, merged